Library/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('books.urls')),
    # url(r'^', include('core.urls')),
]

books/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'books'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', views.register, name='register'),
    url(r'^(?P<book_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^addbook/', views.addbook, name='addbook'),
    url(r'^removebook', views.removeBook, name='removebook'),
    url(r'^search/$', views.search, name='search'),
    url(r'^profile/', views.profile, name='profile'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^adduser/', views.adduser, name='adduser'),
]

core/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views as core_views


urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
]

books/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


# class Profile(models.Model):
#     user = models.OneToOneField(User)
#     roll_no = models.CharField(max_length=10)
#     branch = models.CharField(choices=BRANCH_CHOICES, max_length=6)
#     year = models.CharField(choices=YEAR_CHOICES, max_length=3)
#     birth_date = models.DateField(blank=False, null=False)
#     phone = models.CharField(max_length=10, default='')

BOOK_CHOICES = (
    ('Programming', 'Programming'),
    ('Computer', 'Computer'),
    ('Math', 'Math'),
    ('Economics', 'Economics'),
    ('Accounting', 'Accounting'),
    ('Others', 'Others')
)


class Book(models.Model):
    isbn_no = models.CharField(max_length=100, null=False)
    book_name = models.CharField(max_length=100)
    author_name = models.CharField(max_length=100)
    book_type = models.CharField(max_length=15, choices=BOOK_CHOICES)
    edition = models.IntegerField()
    no_of_books = models.IntegerField()

    def __unicode__(self):
        return self.book_name

books/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Book, Profile


class UserForm(UserCreationForm):
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')

    class Meta:
        model = User
        fields = ('username', 'birth_date', 'password1', 'password2', )


# class DateInput(forms.DateInput):
#     input_type = 'date'


# BRANCH_CHOICES = (
#     ('B.Tech', 'B.Tech'),
#     ('MCA', 'MCA'),
# )

# YEAR_CHOICES = (
#     ('1st', '1st'),
#     ('2nd', '2nd'),
#     ('3rd', '3rd'),
#     ('4th', '4th'),
#     ('5th', '5th'),
# )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'location')


# class ProfileForm(forms.ModelForm):
#     branch = forms.ChoiceField(choices=BRANCH_CHOICES)
#     year = forms.ChoiceField(choices=YEAR_CHOICES)

#     class Meta:
#         model = Profile
#         fields = ['roll_no', 'branch', 'year', 'birth_date', 'phone']
#         widgets = {
#             'birth_date': DateInput(),
#         }

BOOK_CHOICES = (
    ('Programming', 'Programming'),
    ('Computer', 'Computer'),
    ('Math', 'Math'),
    ('Economics', 'Economics'),
    ('Accounting', 'Accounting'),
    ('Others', 'Others')
)


class BookForm(forms.Form):
    isbn_no = forms.CharField(max_length=100)
    book_name = forms.CharField(max_length=100)
    author_name = forms.CharField(max_length=100)
    book_type = forms.ChoiceField(choices=BOOK_CHOICES)
    edition = forms.IntegerField()
    no_of_books = forms.IntegerField()


class RemoveBookForm(forms.Form):
    isbn_no = forms.CharField(max_length=100)

    class Meta:
        model = Book
        fields = ['isbn_no']

books/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import logout

from .forms import UserForm, ProfileForm, BookForm, RemoveBookForm
from .models import Book


@login_required
def home(request):
    username = request.user.username
    book_list = Book.objects.order_by('book_name')[:50]
    return render(request, 'books/home.html', {'book_list': book_list, 'username': username})


def detail(request, book_id):
    if not request.user.is_authenticated():
        return render(request, 'books/login.html')

    username = request.user.username
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'books/detail.html', {'book': book, 'username': username})


# def logout_user(request):
#     logout(request)
#     user_form = UserForm(request.POST or None)
#     context = {
#         "user_form": user_form,
#     }
#     return render(request, 'books/login.html', context)


# def login_user(request):
#     if request.method == "POST":
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(username=username, password=password)
#         if user is not None:
#             if user.is_active:
#                 login(request, user)
#                 book_list = Book.objects.order_by('book_name')[:50]
#                 username = request.user.username
#                 return render(request, 'books/home.html', {'book_list': book_list, 'username': username, })
#             else:
#                 return render(request, 'books/login.html', {'error_message': 'Your account has been disabled'})
#         else:
#             return render(request, 'books/login.html', {'error_message': 'Invalid login'})
#     return render(request, 'books/login.html')


def register(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.profile.bio = profile_form.cleaned_data.get('bio')
            user.profile.location = profile_form.cleaned_data.get('location')
            user.profile.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.birth_date = user_form.cleaned_data.get('birth_date')
            user.save()
            raw_password = user_form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        user_form = UserForm()
        profile_form = ProfileForm()
    return render(request, 'register.html', {'user_form': user_form, 'profile_form': profile_form})


@login_required
def addbook(request):
    username = request.user.username
    if username == 'admin':
        if request.method == 'GET':

            form = BookForm(request.GET)

            if form.is_valid():

                isbn_no = request.GET.get('isbn_no', '')
                book_name = request.GET.get('book_name', '')
                author_name = request.GET.get('author_name', '')
                book_type = request.GET.get('book_type', '')
                edition = request.GET.get('edition', '')
                no_of_books = request.GET.get('no_of_books', '')

                book = Book(
                    isbn_no=isbn_no,
                    book_name=book_name,
                    author_name=author_name,
                    book_type=book_type,
                    edition=edition,
                    no_of_books=no_of_books
                )
                book.save()

                book_list = Book.objects.order_by('book_name')[:50]

                context = {
                    'success_message': "New book is added",
                    'book_list': book_list,
                    'username': username,
                }
                return render(request, 'books/home.html', context)
            else:
                return render(request, 'books/addbook.html', {'error_message': "Data is invalid"})


@login_required
def removeBook(request):
    username = request.user.username
    if username == 'admin':

        if request.method == 'GET':
            form = RemoveBookForm(request.GET)

            if form.is_valid():
                isbn_no = request.GET.get('isbn_no','')
                try:
                    book = Book.objects.get(isbn_no=isbn_no)
                    book.delete()
                    book_list = Book.objects.order_by('book_name')[:50]
                    context = {
                        'success_message': "The book is removed",
                        'book_list': book_list,
                        'username': username,
                    }
                    return render(request, 'books/home.html', context)
                except:
                    return render(request, 'books/removebook.html', {'error_message': "Give correct Id or Name"})
            else:
                return render(request, 'books/removebook.html', {'error_message': "Give correct Id or Name"})


@login_required
def search(request):
    username = request.user.username
    query = request.GET['book_name']
    if query:
        book_list = Book.objects.filter(Q(book_name__icontains=query)).distinct()
        user_list = User.objects.filter(Q(username__startswith=query)).distinct()
        context = {
            'book_list': book_list,
            'user_list': user_list,
            'username': username,
        }
        return render(request, 'books/search.html', context)
    else:
        book_list = Book.objects.order_by('book_name')[:50]
        context = {
            'error_message': "Please Give the book name or username",
            'book_list': book_list,
            'username': username,
        }
        return render(request, 'books/home.html', context)


@login_required
def profile(request):
    username = request.user.username
    user = User.objects.get(username=username)
    return render(request, 'books/profile.html', {'user': user, 'username': username,})


def edit(request):

    if request.POST.get('username'):
        username = request.POST.get('username','')
        user = User.objects.get(username=request.user.username)
        user.username = username
        user.save()

        context = {
            'user': User.objects.get(username=username),
            'username': username,
            'success_message': "Username is changed successfully",
        }
        return render(request, 'books/profile.html', context)

    elif request.POST.get('email'):
        email = request.POST.get('email','')
        user = User.objects.get(username=request.user.username)
        user.email = email
        user.save()

        context = {
            'user': User.objects.get(username=request.user.username),
            'success_message': "Email is changed successfully",
        }
        return render(request, 'books/profile.html', context)

    else:
        if request.user.check_password(request.POST['opassword']):
            npassword = request.POST.get('npassword','')
            cpassword = request.POST.get('cpassword','')

            username = request.user.username
            user = User.objects.get(username=username)

            if npassword == cpassword:
                user.set_password(npassword)
                user.save()

                context = {
                    'user': user,
                    'success_message': "Password is successfully changed."
                }
                return render(request, 'books/profile.html', context)
            else:
                context = {
                    'user': user,
                    'error_message': "Didn't match password!!!"
                }
                return render(request, 'books/profile.html', context)
        else:
            user = User.objects.get(username=request.user.username)
            context = {
                'user': user,
                'error_message': "Old password was incorrect!!!"
            }
            return render(request, 'books/profile.html', context)


def adduser(request):
    if not request.user.is_authenticated():
        return render(request, 'books/login.html')

    username = request.user.username
    if username == 'admin':
        if request.method == 'POST':

            form = BookForm(request.GET)

            if form.is_valid():



                book = User(

                )
                book.save()



                context = {
                    'success_message': "New book is added",
                    'user_list': user_list,
                    'username': username,
                }
                return render(request, 'books/home.html', context)
            else:
                return render(request, 'books/addbook.html', {'error_message': "Data is invalid"})

books/templates/books/addbook.html
{% extends 'books/base.html' %}

{% block title %}Add book to the library{% endblock %}

{% if error_message %}
    <div class="alert alert-danger">
        {{ error_message }}
    </div>
{% endif %}

{% block content %}
    <h1 class="text-center text-uppercase">library management system</h1><br />
    <h2 class="text-center text-uppercase">add books to the library</h2><br />
    <form class="form-horizontal" method="get" action="{% url 'books:addbook' %}">
        <div class="form-group">
            <label for="isbn_no" class="col-sm-2 control-label">ISBN No: </label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="isbn_no" name="isbn_no" placeholder="ISBN No">
            </div>
        </div>

        <div class="form-group">
            <label for="book_name" class="col-sm-2 control-label">Book Name: </label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="book_name" name="book_name" placeholder="Book Name">
            </div>
        </div>

        <div class="form-group">
            <label for="author_name" class="col-sm-2 control-label">Author Name: </label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="author_name" name="author_name" placeholder="Author Name">
            </div>
        </div>

        <div class="form-group">
            <label for="book_type" class="col-sm-2 control-label">Book Type: </label>
            <div class="col-sm-5">
                <select>
                    {% for choice in field.choices %}
                        <option name="b_id" value="{{choice.0}}">{{choice.1}}</option>
                        print choice.0
                        print choice.1
                    {% endfor %}
                </select>
                <input type="text" class="form-control" id="book_type" name="book_type" placeholder="Book Type">
            </div>
        </div>

        <div class="form-group">
            <label for="edition" class="col-sm-2 control-label">Edition: </label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="edition" name="edition" placeholder="edition eg. 1, 2 etc">
            </div>
        </div>

        <div class="form-group">
            <label for="no_of_books" class="col-sm-2 control-label">No of Books: </label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="no_of_books" name="no_of_books" placeholder="No of books">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-5">
                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-save"></span> Save</button>
            </div>
        </div>
    </form>
{% endblock %}

books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'books/img/title.png' %}">
    <link rel="stylesheet" href="{% static 'books/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'books/css/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="{% static 'books/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'books/js/bootstrap.min.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'books:home' %}">Library</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% block books_active %}{% endblock %}"><a href="{% url 'books:home' %}">Books</a></li>
                    <li class="{% block profile_active %}{% endblock %}"><a href="{% url 'books:profile' %}">Profile</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% block search %}
                    {% endblock %}
                    {% if username == 'admin' %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'books:addbook' %}">
                                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Books
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="{% url 'books:adduser' %}">
                                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Add Users
                                    </a>
                                </li>

                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span> Remove <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'books:removebook' %}">
                                        <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>&nbsp; Remove Books
                                    </a>
                                </li>
                                <li class="divider"></li>
                            </ul>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'books:logout_user' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>

        </div>
    </nav>
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
    <script src="{% static 'books/js/main.js' %}"></script>
</body>
</html>

books/templates/books/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'books/img/title.png' %}">
    <link rel="stylesheet" href="{% static 'books/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'books/css/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="{% static 'books/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'books/js/bootstrap.min.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'books:home' %}">Library</a>
            </div>

            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="{% block register_active %}{% endblock %}"><a href="{% url 'books:register' %}">Register</a></li>
                    <li class="{% block login_active %}{% endblock %}"><a href="{% url 'books:login_user' %}">Log In</a></li>
                </ul>
            </div>

        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

books/templates/books/detail.html
{% extends 'books/base.html' %}

{% block title %}book details{% endblock %}

{% block content %}
    <h2>Hello {{ username }}</h2>
    <h3>{{ book.book_name }}</h3>
    <h3>{{ book.book_name }} is available ( {{ book.no_of_books }} ) </h3>
    <h3>Author Name: {{ book.author_name }}</h3><br />
{% endblock %}

books/templates/books/home.html
{% extends 'books/base.html' %}

{% block title %}Book home page{% endblock %}

{% block books_active %}active{% endblock %}

{% block search %}
    <form class="navbar-form navbar-left" action="{% url 'books:search' %}" method="get">
        <div class="form-group">
            <input type="text" class="form-control" name="book_name" placeholder="Book Name {% if username == 'admin' %} or User Name {% endif %}">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
    </form>
{% endblock %}

{% block content %}
    <h1><p class="text-uppercase text-center">Library Management System</p></h1>
    <h2>Hello {{ username }}</h2>
    <h3>Book List</h3>

    {% if success_message %}
        <div class="alert alert-success">
            {{ success_message }}
        </div>
    {% endif %}
    {% if error_message %}
        <div class="alert alert-danger">
            {{ error_message }}
        </div>
    {% endif %}

    {% if book_list %}
        <table class="table table-hover">
            <tr>
                <th>ISBN No</th>
                <th>Book Name</th>
                <th>Author Name</th>
                <th>Book Type</th>
                <th>Edition</th>
                <th>No. of Books</th>
            </tr>
            {% for book in book_list %}
                <tr data-toggle="modal" data-target="#{{ book.isbn_no }}">
                    <td>{{ book.isbn_no }}</td>
                    <td>{{ book.book_name }}</td>
                    <td>{{ book.author_name }}</td>
                    <td>{{ book.book_type }}</td>
                    <td>{{ book.edition }}</td>
                    <td>{{ book.no_of_books }}</td>
                </tr>
            {% endfor %}
        </table>
        {% for book in book_list %}
            <div class="modal fade" id="{{ book.isbn_no }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabelName" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="myModalLabelName"> Book Details </h4>
                            </div>
                            <div class="modal-body">
                                <h2> {{ book.book_name }} </h2>
                                <h3> {{ book.author_name }} </h3>
                                <h3> {{ book.no_of_books }} </h3>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
    {% else %}
        <h3 style="color: red;">No book is available</h3>
    {% endif %}
{% endblock %}

books/templates/books/login.html
{% extends 'books/base_visitor.html' %}

{% block title %}login page{% endblock %}
{% block login_active %}active{% endblock %}

{% block content %}
    <h2>Log in to My Site</h2>
  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Log in</button>
    <a href="{% url 'register' %}">New to My Site? Sign up</a>
  </form>
{% endblock %}

books/templates/books/register.html
{% extends 'books/base_visitor.html' %}

{% block title %}register page{% endblock %}
{% block register_active %}active{% endblock %}

{% block content %}
    <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in user_form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
      {% for field in profile_form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

books/templates/books/removebook.html
{% extends 'books/base.html' %}

{% block title %}Remove book to the library{% endblock %}

{% if error_message %}
    <h3 style="color: red;">{{ error_message }}</h3>
{% endif %}

{% block content %}
    <h1 class="text-uppercase text-center">remove book</h1>
    <form class="form-horizontal" method="get" action="{% url 'books:removebook' %}">
        <div class="form-group">
            <label for="isbn_no" class="col-sm-2 control-label">ISBN No: </label>
            <div class="col-sm-5">
                <input type="text" class="form-control" id="isbn_no" name="isbn_no" placeholder="ISBN No">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-5">
                <button type="submit" class="btn btn-warning"><span class="glyphicon glyphicon-remove"></span> Remove</button>
            </div>
        </div>
    </form>
{% endblock %}

books/templates/books/search.html
{% extends 'books/base.html' %}

{% block title %}Search Page{% endblock %}

{% block content %}
    <h2>Hello {{ username }}</h2>
    {% if book_list or user_list %}
        <h3>Searched Results are: </h3>
        {% if book_list %}
            <h3>Book List: </h3>
            <table class="table table-hover">
                <tr>
                    <th>ISBN No</th>
                    <th>Book Name</th>
                    <th>Author Name</th>
                    <th>Book Type</th>
                    <th>Edition</th>
                    <th>No. of Books</th>
                </tr>
                {% for book in book_list %}
                    <tr>
                        <td>{{ book.isbn_no }}</td>
                        <td>{{ book.book_name }}</td>
                        <td>{{ book.author_name }}</td>
                        <td>{{ book.book_type }}</td>
                        <td>{{ book.edition }}</td>
                        <td>{{ book.no_of_books }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
        {% if user_list and username == 'admin' %}
            <h3>User List:</h3>
            <table class="table table-hover">
                <tr>
                    <th>User Name</th>
                    <th>Email</th>
                </tr>
                {% for user in user_list %}
                    <tr>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
    {% else %}
        <h3 style="color: red;">No Book or User is available</h3>
    {% endif %}
{% endblock %}